### PR TITLE
Css style type-safe DSL

### PR DESCRIPTION
**Pull request by vlipovetskii**
Code is self-explanatory :)

### CODE REVIEW

**Comment by mvysny** [comment]
Thank you, looks great! Could you please add an example code how you would use the API, and how it simplifies development as opposed to vanilla Vaadin API?

I like this as an initial work; yet supporting entire CSS may be a lot of work. I've seen the work done at https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-css - maybe we could use that instead, and integrate that into Karibu-DSL?

**Comment by vlipovetskii** [comment]
"example code how you would use the API"
Please take a look at the example in comments in KCssStyle.kt. 
/*
val cssBlueColorStyle: KCssStyleBlock = {
    color = KCssColor.Blue.value
}
 cssStyleBlock {
    cssBlueColorStyle()
    margin.left = "0px"
}
*/

"how it simplifies development as opposed to vanilla Vaadin API?" 
See. my article https://medium.com/@vlipovetskii/kotlin-css-style-type-safe-dsl-for-vaadin-10-5423d07c2f89. 
BTW, I have reworked how to process compex properties like margin-*. There is an update in the article. 
I have added the commit with changes to PR.

"yet supporting entire CSS may be a lot of work" - sure. Actually, I expand the supporting classes and/or DSL following the practical needs of my projects. CSS Style DSL now provides open architecture to add new css properties. You, me and other developers can expand it by pull requests easily.   

kotlin-css is part of Kotlin wrappers for popular JavaScript libraries. If I understand correctly, it is intended to Kotlin as a replacement for JavaScript. I.e. it is for front-end, while DSL that we are discussing is server-side based. I don't know JS and don't want to learn it, and this is why I am leveraging Vaadin :)

I am not an expert in CSS as well. If it's convinient for you, please give me the prioritized list of css properties and I will convert them into DSL following the priorities.

**Comment by mvysny** [comment]
> kotlin-css is part of Kotlin wrappers for popular JavaScript libraries. If I understand correctly, it is intended to Kotlin as a replacement for JavaScript. I.e. it is for front-end, while DSL that we are discussing is server-side based. I don't know JS and don't want to learn it, and this is why I am leveraging Vaadin :)

I completely understand, I also tend to distance myself as far from JS as possible :-D Yet the `kotlin-css` module is multi-platform: there is a jar for JVM which has nothing to do at all with JS. It's located in this bintray repo: https://bintray.com/kotlin/kotlin-js-wrappers/kotlin-css 

I kinda like the `LinearDimension` class which supports most CSS sizes along with `calc()`: we could feed `LinearDimension` directly to `Component.w` extension method which would allow us to write code like `label.w = 30.px`. The problem with `kotlin-css` is that it's not yet released (there's no stable release and it's not on jcenter nor Maven Central).

Don't get me wrong: I like your code, but I feel that it would be better to have the CSS code as a complete external library, with tests and everything. Maybe you could focus on writing an integration layer of Karibu-DSL and JVM kotlin-css instead? You can pull in `kotlin-css` by adding the `https://kotlin.bintray.com/kotlin-js-wrappers/` repository and adding dependency on `compile 'org.jetbrains:kotlin-css:1.0.0-pre.59-kotlin-1.3.0'`

**Comment by mvysny** [comment]
I've played with the kotlin-css a bit: just add this to your build.gradle.kts:

```
repositories {
    maven { setUrl("https://kotlin.bintray.com/kotlin-js-wrappers/") }
}
dependencies {
    // CSS DSL
    compile("org.jetbrains:kotlin-css-jvm:1.0.0-pre.59-kotlin-1.3.0")
}
```
Then you can
```kotlin
var HasSize.w: LinearDimension
    get() = LinearDimension(width)
    set(value) { width = value.value }
var HasSize.h: LinearDimension
    get() = LinearDimension(height)
    set(value) { height = value.value }

fun Component.css(block: CSSBuilder.()->Unit) {
    val builder = CSSBuilder()
    block(builder)
    val style = element.style
    builder.declarations.forEach { key, value ->
        style[key.hyphenize()] = value.toString()
    }
}
```
which allows you to write
```kotlin
button.w = 20.px
button.css {
  backgroundColor = Color.azure
  width = 45.px
}
```
The kotlin-css comes with lot of the code out of the box - just check out all of the properties. However, it indeed looks a bit complicated.

**Comment by vlipovetskii** [comment]
Super ! Thank you very much !

I have created some more propeties (which are required for my current project - see below) , but you are are right. kotlin-css together with your extension functions is much better solution. I will replace my Kcss* with it. 
KCssBackgroundProperty.kt, KCssBorderProperty.kt, KCssColorProperty.kt, KCssMarginProperty.kt, KCssSide.kt, KCssStyleAbstractPropertyA.kt

Also, I was going to implement whiteSpace, wordWrap since I need them, but now I shouldn't do it.

How do you think, maybe it's better to rely on HasStyle instead of Component ?
Something like

fun HasStyle.css(block: CSSBuilder.()->Unit) {
    val builder = CSSBuilder()
    block(builder)
    // val style = element.style
    builder.declarations.forEach { key, value ->
        style[key.hyphenize()] = value.toString()
    }
}

or in a more functional style 

fun HasStyle.css(block: CSSBuilder.()->Unit) =
    CSSBuilder().apply {
      block()
      declarations.forEach { key, value ->
        style[key.hyphenize()] = value.toString()
    }
}

**Comment by jhult** [comment]
I ended up using [`kotlin-css`](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-css) with the following code:

```
import com.github.mvysny.karibudsl.v10.VaadinDsl
import com.github.mvysny.karibudsl.v10.icon
import com.vaadin.flow.component.HasComponents
import com.vaadin.flow.component.HasSize
import com.vaadin.flow.component.HasStyle
import com.vaadin.flow.component.icon.Icon
import com.vaadin.flow.component.icon.VaadinIcon
import kotlinx.css.CSSBuilder
import kotlinx.css.LinearDimension
import kotlinx.css.height
import kotlinx.css.hyphenize
import kotlinx.css.width

/**
 * @see https://github.com/mvysny/karibu-dsl/pull/11
 */

var HasSize.w: LinearDimension
    get() = LinearDimension(width)
    set(value) { width = value.value }
var HasSize.h: LinearDimension
    get() = LinearDimension(height)
    set(value) { height = value.value }

@VaadinDsl
fun HasStyle.css(block: @VaadinDsl CSSBuilder.() -> Unit): CSSBuilder {
    return CSSBuilder().apply {
        block()
        val style = element.style
        declarations.forEach { (key, value) ->
            style[key.hyphenize()] = value.toString()
        }
        this@css.addClassNames(*classes.toTypedArray())
    }
}

@VaadinDsl
fun CSSBuilder.addClassNames(vararg classNames: String) {
    @Suppress("UNCHECKED_CAST")
    (classNames as Array<String>).unaryPlus()
}

@VaadinDsl
fun (@VaadinDsl HasComponents).icon(icon: VaadinIcon, size: LinearDimension = VAL_SIZE_MEDIUM) {
    icon(icon) {
        setSize(size)
    }
}

@VaadinDsl
internal fun (@VaadinDsl Icon).setSize(size: LinearDimension = VAL_SIZE_MEDIUM) {
    css {
        width = size
        height = size
    }
}
```

**Comment by mvysny** [comment]
This looks good! @jhult could you please create a new PR with your proposal? Also could you add examples of how to use each function?

**Comment by mvysny** [comment]
Closing as duplicate of #14

**Pull request closed without merging**
